# Generated by Django 5.0.4 on 2026-05-17 14:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IceCreamLogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="ice_cream_logo/")),
                ("text", models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IceCreamTasteTags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                (
                    "weight",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCriteriaReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mark", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductTasteCriteria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTasting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(blank=True, max_length=127, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tea_flavor_combination", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTastingUserMark",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_nominated", models.BooleanField(default=False)),
                (
                    "podium_place",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TasteCriteria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("grade", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Tasting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TastingParticipation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("ice_cream", "Мороженое"), ("tea", "Чай")], max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("number", models.IntegerField(blank=True, default=None, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("composition", models.JSONField(blank=True, default=list)),
                ("image", models.ImageField(blank=True, null=True, upload_to="products/")),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.line",
                    ),
                ),
                (
                    "taste_tags",
                    models.ManyToManyField(blank=True, related_name="products", to="catalog.icecreamtastetags"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductIceCreamLogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("logo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.icecreamlogo")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.product")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="logos",
            field=models.ManyToManyField(
                blank=True, related_name="products", through="catalog.ProductIceCreamLogo", to="catalog.icecreamlogo"
            ),
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("global_comment", models.TextField(blank=True, null=True)),
                ("self_comment", models.TextField(blank=True, null=True)),
                ("tasted", models.BooleanField(default=False)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("composition", models.JSONField(blank=True, default=list)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="catalog.product"
                    ),
                ),
                (
                    "taste_tags",
                    models.ManyToManyField(blank=True, related_name="reviews", to="catalog.icecreamtastetags"),
                ),
            ],
        ),
    ]
