# Generated by Django 5.0.4 on 2026-05-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="productcriteriareview",
            name="product_review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="criteria_reviews", to="catalog.productreview"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tasters",
            field=models.ManyToManyField(
                blank=True, related_name="tasted_products", through="catalog.ProductReview", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="producttastecriteria",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.product"),
        ),
        migrations.AddField(
            model_name="producttasting",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.product"),
        ),
        migrations.AddField(
            model_name="producttastingusermark",
            name="product_tasting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_marks", to="catalog.producttasting"
            ),
        ),
        migrations.AddField(
            model_name="producttastingusermark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_tasting_marks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producttastecriteria",
            name="criteria",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.tastecriteria"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="taste_criteria",
            field=models.ManyToManyField(
                blank=True, related_name="reviews", through="catalog.ProductCriteriaReview", to="catalog.tastecriteria"
            ),
        ),
        migrations.AddField(
            model_name="productcriteriareview",
            name="criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="catalog.tastecriteria"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="taste_criteria",
            field=models.ManyToManyField(
                blank=True, related_name="products", through="catalog.ProductTasteCriteria", to="catalog.tastecriteria"
            ),
        ),
        migrations.AddField(
            model_name="tasting",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="tastings", through="catalog.ProductTasting", to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="producttastingusermark",
            name="tasting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_marks", to="catalog.tasting"
            ),
        ),
        migrations.AddField(
            model_name="producttasting",
            name="tasting",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.tasting"),
        ),
        migrations.AddField(
            model_name="tastingparticipation",
            name="tasting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="catalog.tasting"
            ),
        ),
        migrations.AddField(
            model_name="tastingparticipation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasting_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasting",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="tastings", through="catalog.TastingParticipation", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(fields=("user", "product"), name="uniq_user_product_review"),
        ),
        migrations.AddConstraint(
            model_name="producttastingusermark",
            constraint=models.UniqueConstraint(
                fields=("user", "product_tasting"), name="uniq_user_product_tasting_mark"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttastingusermark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("podium_place__isnull", False)),
                fields=("user", "tasting", "podium_place"),
                name="uniq_user_tasting_podium_place",
            ),
        ),
        migrations.AddConstraint(
            model_name="tastingparticipation",
            constraint=models.UniqueConstraint(fields=("tasting", "user"), name="uniq_tasting_user"),
        ),
    ]
