# Generated by Django 5.0.4 on 2026-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="interesting_fact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producttastecriteria",
            name="for_tea_combination",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasting",
            name="result_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="producttasting",
            name="tea_flavor_combination",
        ),
        migrations.AddField(
            model_name="producttasting",
            name="tea_flavor_combination",
            field=models.ManyToManyField(blank=True, related_name="+", to="catalog.product"),
        ),
    ]
