# Generated by Django 5.0.4 on 2026-05-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_interesting_fact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tastecriteria",
            name="grade",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
