# Generated by Django 5.0.4 on 2026-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_tastecriteria_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="tastecriteria",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
