# Generated by Django 5.0.4 on 2026-05-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_tastecriteria_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tastecriteria",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="tastecriteria",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
