# Generated by Django 5.0.4 on 2026-05-18 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_result_phrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="icecreamlogo",
            name="intro_name",
            field=models.CharField(default="", max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="icecreamlogo",
            name="image",
            field=models.FileField(
                upload_to="ice_cream_logo/",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["png", "jpg", "jpeg", "svg"])
                ],
            ),
        ),
    ]
