# Generated by Django 5.0.4 on 2026-05-18 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_icecreamlogo_intro_name_product_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["png", "jpg", "jpeg", "svg"])
                ],
            ),
        ),
    ]
