# Generated by Django 5.0.4 on 2026-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="icecreamlogo",
            name="type",
            field=models.CharField(choices=[("ice_cream", "Мороженое"), ("tea", "Чай")], default="tea"),
        ),
    ]
