# Generated by Django 5.0.4 on 2026-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_icecreamlogo_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("show_share_link", models.BooleanField(default=False)),
                ("share_text", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Конфиг",
                "verbose_name_plural": "Конфиг",
            },
        ),
    ]
