# Generated by Django 5.0.4 on 2026-05-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircleChart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="IceCreamTasteTags",
            new_name="TasteTags",
        ),
        migrations.AddField(
            model_name="product",
            name="tea_index",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_nickname",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_plucking_season",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_price_per_gram",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_sort",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="tastecriteria",
            name="orientation",
            field=models.CharField(
                choices=[("horizontal", "Горизонтальная"), ("vertical", "Вертикальная")], default="horizontal"
            ),
        ),
        migrations.AddField(
            model_name="tastecriteria",
            name="chart",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.circlechart",
            ),
        ),
    ]
