# Generated by Django 5.0.4 on 2026-05-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_circlechart_rename_icecreamtastetags_tastetags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasting",
            name="type",
            field=models.CharField(choices=[("ice_cream", "Мороженое"), ("tea", "Чай")], default="ice_cream"),
        ),
    ]
