# Generated by Django 5.0.4 on 2026-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_tasting_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tastecriteria",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[("horizontal", "Горизонтальная"), ("vertical", "Вертикальная")],
                default=None,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="tastecriteria",
            constraint=models.CheckConstraint(
                check=models.Q(("chart__isnull", False), ("orientation__isnull", False), _negated=True),
                name="tastecriteria_chart_or_orientation_not_both",
            ),
        ),
    ]
