# Generated by Django 5.0.4 on 2026-05-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_tastecriteria_orientation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlechart",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
