# Generated by Django 5.0.4 on 2026-05-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_circlechart_order_alter_product_composition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circlechart",
            options={"ordering": ["order", "id"]},
        ),
    ]
