# Generated by Django 5.0.4 on 2026-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_circlechart_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlechart",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
