# Generated by Django 5.0.4 on 2026-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_circlechart_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tea_price_per_gram",
        ),
        migrations.AddField(
            model_name="product",
            name="tea_geography",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_measure_unit",
            field=models.CharField(blank=True, default="грамм", max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_price",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
