# Generated by Django 5.0.4 on 2026-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_remove_product_tea_price_per_gram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlechart",
            name="label_placement",
            field=models.CharField(choices=[("vertices", "на вершинах"), ("edges", "на рёбрах")], default="edges"),
        ),
    ]
