# Generated by Django 5.0.4 on 2026-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_circlechart_label_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tea_rubrucator",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
