# Generated by Django 5.0.4 on 2026-05-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_product_tea_rubrucator"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CircleChart",
            new_name="Chart",
        ),
    ]
