# Generated by Django 5.0.4 on 2026-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_rename_circlechart_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="chart_type",
            field=models.CharField(choices=[("circle", "Круговая"), ("plot", "График")], default="circle"),
        ),
    ]
