# Generated by Django 5.0.4 on 2026-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_chart_chart_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="x_axis",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="chart",
            name="x_axis_name",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="y_axis",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="chart",
            name="y_axis_name",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="productcriteriareview",
            name="x",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="productcriteriareview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("x__isnull", True)),
                fields=("product_review", "criteria"),
                name="uniq_criteria_review_no_x",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcriteriareview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("x__isnull", False)),
                fields=("product_review", "criteria", "x"),
                name="uniq_criteria_review_per_x",
            ),
        ),
    ]
