# Generated by Django 5.0.4 on 2026-05-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_chart_x_axis_chart_x_axis_name_chart_y_axis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasteBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="chart",
            name="taste_block",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charts",
                to="catalog.tasteblock",
            ),
        ),
        migrations.AddField(
            model_name="tastecriteria",
            name="taste_block",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criterias",
                to="catalog.tasteblock",
            ),
        ),
        migrations.CreateModel(
            name="TastingTasteBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "taste_block",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.tasteblock"),
                ),
                ("tasting", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.tasting")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="tasting",
            name="taste_blocks",
            field=models.ManyToManyField(
                blank=True, related_name="tastings", through="catalog.TastingTasteBlock", to="catalog.tasteblock"
            ),
        ),
        migrations.AddConstraint(
            model_name="tastingtasteblock",
            constraint=models.UniqueConstraint(fields=("tasting", "taste_block"), name="uniq_tasting_taste_block"),
        ),
    ]
