# Generated by Django 5.0.4 on 2026-05-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_tasteblock_chart_taste_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="product_tasting",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalog.producttasting",
            ),
        ),
        migrations.CreateModel(
            name="ProductTastingTasteBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product_tasting",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.producttasting"),
                ),
                (
                    "taste_block",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.tasteblock"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="producttasting",
            name="taste_blocks",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_tastings",
                through="catalog.ProductTastingTasteBlock",
                to="catalog.tasteblock",
            ),
        ),
        migrations.CreateModel(
            name="ProductTastingTasteCriteria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("for_tea_combination", models.BooleanField(default=False)),
                (
                    "criteria",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.tastecriteria"),
                ),
                (
                    "product_tasting",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.producttasting"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="producttasting",
            name="taste_criteria",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_tastings",
                through="catalog.ProductTastingTasteCriteria",
                to="catalog.tastecriteria",
            ),
        ),
        migrations.AddConstraint(
            model_name="producttastingtasteblock",
            constraint=models.UniqueConstraint(
                fields=("product_tasting", "taste_block"), name="uniq_product_tasting_taste_block"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttastingtastecriteria",
            constraint=models.UniqueConstraint(
                fields=("product_tasting", "criteria"), name="uniq_product_tasting_criteria"
            ),
        ),
    ]
