# Generated by Django 5.0.4 on 2026-05-29 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_move_evaluation_to_product_tasting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttastecriteria",
            name="criteria",
        ),
        migrations.RemoveField(
            model_name="producttastecriteria",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="taste_criteria",
        ),
        migrations.RemoveField(
            model_name="tastingtasteblock",
            name="taste_block",
        ),
        migrations.RemoveField(
            model_name="tastingtasteblock",
            name="tasting",
        ),
        migrations.RemoveField(
            model_name="tasting",
            name="taste_blocks",
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product_tasting",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalog.producttasting",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                fields=("user", "product_tasting"), name="uniq_user_product_tasting_review"
            ),
        ),
        migrations.DeleteModel(
            name="ProductTasteCriteria",
        ),
        migrations.DeleteModel(
            name="TastingTasteBlock",
        ),
    ]
