# Generated by Django 5.0.4 on 2026-05-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_remove_producttastecriteria_criteria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhraseTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default=None, max_length=127, null=True)),
                (
                    "template",
                    models.TextField(
                        help_text="Текст с токенами {blank} на месте пропусков, напр.: «Этот чай напомнил мне {blank}, а также {blank}.»"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "taste_block",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phrase_templates",
                        to="catalog.tasteblock",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PhraseTemplateReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answers", models.JSONField(default=list)),
                (
                    "phrase_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="catalog.phrasetemplate"
                    ),
                ),
                (
                    "product_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phrase_reviews",
                        to="catalog.productreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTastingPhraseTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "phrase_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.phrasetemplate"),
                ),
                (
                    "product_tasting",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.producttasting"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="producttasting",
            name="phrase_templates",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_tastings",
                through="catalog.ProductTastingPhraseTemplate",
                to="catalog.phrasetemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="phrasetemplatereview",
            constraint=models.UniqueConstraint(
                fields=("product_review", "phrase_template"), name="uniq_phrase_template_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttastingphrasetemplate",
            constraint=models.UniqueConstraint(
                fields=("product_tasting", "phrase_template"), name="uniq_product_tasting_phrase_template"
            ),
        ),
    ]
