# Generated by Django 5.0.4 on 2026-05-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_phrasetemplate_phrasetemplatereview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTastingChart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("chart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.chart")),
                (
                    "product_tasting",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.producttasting"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="producttasting",
            name="charts",
            field=models.ManyToManyField(
                blank=True, related_name="product_tastings", through="catalog.ProductTastingChart", to="catalog.chart"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttastingchart",
            constraint=models.UniqueConstraint(fields=("product_tasting", "chart"), name="uniq_product_tasting_chart"),
        ),
    ]
