# Generated by Django 5.0.4 on 2026-05-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_backfill_product_tasting_charts"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeTextPrompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "taste_block",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_text_prompts",
                        to="catalog.tasteblock",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FreeTextPromptReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(blank=True, default="")),
                (
                    "free_text_prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="catalog.freetextprompt"
                    ),
                ),
                (
                    "product_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_text_reviews",
                        to="catalog.productreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTastingFreeTextPrompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "free_text_prompt",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.freetextprompt"),
                ),
                (
                    "product_tasting",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.producttasting"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="producttasting",
            name="free_text_prompts",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_tastings",
                through="catalog.ProductTastingFreeTextPrompt",
                to="catalog.freetextprompt",
            ),
        ),
        migrations.AddConstraint(
            model_name="freetextpromptreview",
            constraint=models.UniqueConstraint(
                fields=("product_review", "free_text_prompt"), name="uniq_free_text_prompt_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttastingfreetextprompt",
            constraint=models.UniqueConstraint(
                fields=("product_tasting", "free_text_prompt"), name="uniq_product_tasting_free_text_prompt"
            ),
        ),
    ]
