# Generated by Django 5.0.4 on 2026-05-30 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_freetextprompt_freetextpromptreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasting",
            name="show_podium_candidates",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="producttastingusermark",
            name="podium_place",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
