# Generated by Django 5.0.4 on 2026-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_tasting_show_podium_candidates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttastingtasteblock",
            name="show_tags",
            field=models.BooleanField(default=False, verbose_name="Отображать теги в данном блоке"),
        ),
    ]
