# Generated by Django 5.0.4 on 2026-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_producttastingtasteblock_show_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tea_latitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_longitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
