# Generated by Django 5.0.4 on 2026-05-30 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_product_tea_latitude_product_tea_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.FileField(
                        upload_to="product_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="producttasting",
            name="photos",
            field=models.ManyToManyField(blank=True, related_name="product_tastings", to="catalog.productphoto"),
        ),
        migrations.AddField(
            model_name="producttastingtasteblock",
            name="photos",
            field=models.ManyToManyField(blank=True, related_name="taste_blocks", to="catalog.productphoto"),
        ),
    ]
