# Generated by Django 5.0.4 on 2026-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0035_productphoto_producttasting_photos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tea_latitude",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tea_longitude",
        ),
        migrations.AddField(
            model_name="product",
            name="altitude",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="color_type_name",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tea_cultivar",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
