# Generated by Django 5.0.4 on 2026-05-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_remove_product_tea_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="altitude",
            new_name="tea_altitude",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="color_type_name",
            new_name="tea_color_type_name",
        ),
    ]
